### ISSUE TITLE
Forza Horizon 5 FIX

### ISSUE THREAD

**Issue by leowerlich** [PAXANDDOS/ForzaHorizon4Fix#1]
Hello, can you please make a forza horizon 5 automatic bat file like this?

The game folder is the following: 
C:\Program Files\WindowsApps\Microsoft.624F8B84B80_3.405.2.0_x64__8wekyb3d8bbwe

Trying to adjust your script, but it didn't worked.

**Comment by PAXANDDOS** [comment]
Hey! Thanks for the attention to this fix and for creating an issue!
Is this problem still relevant in Forza Horizon 5? I was hoping they fixed it there...
Unfortunately, I don't own FH5 yet :sob: So can't really test things out. But maybe I can guide you on which things to find and change if you're ok with that.

You'll need to see the line **32** which is 
`start /high explorer.exe shell:appsFolder\Microsoft.SunriseBaseGame_8wekyb3d8bbwe!SunriseReleaseFinal`
and change the shell command to run the FH5 package. So basically it's `shell:appsFolder\PACKAGE!APPID`. As I see from the game directory you mentioned, the package should be `Microsoft.624F8B84B80_8wekyb3d8bbwe`. And the AppID you can find in the folder in the `AppManifest.xml` file, find this tag in the file `<Application Id=` and copy the application ID.

Finally, replace line **32** to `
start /high explorer.exe shell:appsFolder\Microsoft.624F8B84B80_8wekyb3d8bbwe!APPID`.

And the last thing is to find the line **35** and replace `ForzaHorizon4.exe` with `ForzaHorizon5.exe` (see Task manager Details tab while the game is running to find its name if that won't work).

Hope nothing else has changed from FH4 to FH5, should be that simple.  Let me know if this helps! And I will look forward to owning FH5 to make another script. Have a good day! :blush:

**Comment by 0utplay** [comment]
Hey, so I tested this. The appid is: `Forzahorizon5` that leads to 
`start /high explorer.exe shell:appsFolder\Microsoft.624F8B84B80_8wekyb3d8bbwe!Forzahorizon5`
The name in line 35 is `ForzaHorizon5.exe`

**Comment by PAXANDDOS** [comment]
> Hey, so I tested this. The appid is: `Forzahorizon5` that leads to `start /high explorer.exe shell:appsFolder\Microsoft.624F8B84B80_8wekyb3d8bbwe!Forzahorizon5` The name in line 35 is `ForzaHorizon5.exe`

Good news, thanks! And how does it work? Is everything ok? If yes, I'll add a new file to the repository

**Comment by 0utplay** [comment]
It worked how its supposed to, but I did no tests of running the game for multiple hours

**Comment by PAXANDDOS** [comment]
Seems fine actually. I also have got some requests on Telegram about Forza Horizon 5 fix. I've changed the batch file with the information that you provided and got positive results, people telling me that everything works fine. I will now add the new fix to this repository, thanks! :heart: :fire: 

Also, maybe I found the real source of the problem... It may be caused by Teredo service, I found about it when was playing FH4 last summer. I also tried to make another fix, totally different, which interrupts registry and teredo services, but also could not test it properly, and don't actually remember, does it work or not. And I guess I'll never know because I moved to Windows 11 and FH4 works perfectly even without fixes. Not sharing the file here because it may damage your teredo service unless you remember its previous state. If someone will get tired of dead explorer, I can give some guidelines and you can test it, DM me on Telegram then `@paxanddos`. Have a good day everyone!
