### ISSUE TITLE
No Xbox Game Bar available

### ISSUE THREAD

**Issue by vieleba22** [PAXANDDOS/ForzaHorizon4Fix#2]
Hi!
Program seems to work but I have one problem.
Basically after killing explorer.exe task I cant use my xbox game bar that unallows me to invite my friends to party or accept their invites...
Does anyone have any idea that could help me with it?

**Comment by PAXANDDOS** [comment]
Hey! Actually, I know about this issue for quite a while now... A lot of things stop working after explorer.exe is killed, including Xbox Game Bar, because every shortcut command with the "Win" button in it won't work. And to be honest, I have no idea how to fix this :pensive: I usually join my friends via the game menu. 
Press the escape button / Start button while in-game and on the right will be blocked which allows you to join available friends' lobbies.
