### ISSUE TITLE
Steam version support

### ISSUE THREAD

**Issue by sprlptr48** [PAXANDDOS/ForzaHorizon4Fix#6]
Would this work with Forza Horizon 4 on steam if i edit the folders in the .bat files? Is it not compatible with Steam?

**Comment by PAXANDDOS** [comment]
These files are originally not meant to work with Steam because the script uses the shell to launch UWP applications. Games from Windows Store are UWP so they require some extra headache to launch via batch file.
Also, you're the first one on my mind who reports that Forza crashes on Steam as well, I thought it was good there.

Anyways, I believe you can still launch it, just will have to edit the start command.
Let's say you want to edit [ForzaHorizon4_light.bat](https://github.com/PAXANDDOS/ForzaHorizonFix/blob/master/ForzaHorizon4_light.bat), you would need to change 7th line as follows and provide a path to its executable:

```diff
5  echo Waiting for Forza Horizon 4 to finally launch and then killing explorer.exe.
6 
-  start /high explorer.exe shell:appsFolder\Microsoft.SunriseBaseGame_8wekyb3d8bbwe!SunriseReleaseFinal
+  start /high D:\Steam\steamapps\common\ ...
8  SetLocal EnableExtensions
9  SetLocal ENABLEDELAYEDEXPANSION
```

I can't guarantee that everything will work as expected, or will work at all, but still worth a shot

**Comment by sprlptr48** [comment]
Writing this to inform you, the fix did indeed terminate explorer.exe.
But it still crashes for me so my problem probably weren't related to that.

**Comment by PAXANDDOS** [comment]
Sorry to hear that, but honestly I was almost sure that running my script against Steam won't help. Try searching results on steam discussions/guides or generally googling problem for Steam, and good luck!
